[module]
  [module.hugoVersion]
    extended = true
    min = "0.120.0"
  [[module.imports]]
    path = "github.com/simple-icons/simple-icons"
      [[module.imports.mounts]]
        source = "icons"
        target = "assets/svg/simple-icons"
      [[module.imports.mounts]]
        source = "_data"
        target = "data"
