name: sync-version
on:
  push:
    branches:
      - master
  schedule:
    # We specifically set this following Simple Icon's GitHub workflow schedule:
    # 10 hours after release.
    - cron: '0 10 * * 0' # 10:00 at every Sunday

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run 'make update'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Sync Simple Icons to Hugo module
